# /// script
# requires-python = ">=3.11"
# dependencies = ["pvlib==0.16.1"]
# [tool.uv]
# exclude-newer = "2026-10-06T00:00:00Z"
# ///
"""Fixtures for pvkit irradiance/extra-radiation from pvlib.irradiance.get_extra_radiation.

Run: uv run scripts/fixtures/irradiance-extra-radiation.py
Writes packages/pvkit/src/models/irradiance/extra-radiation/extra-radiation-fixtures.json and
earth-radius-terms.ts (SPA R0..R4 terms copied from pvlib.spa, used by method "nrel").
"""

import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import pvlib
from pvlib import spa

DIR = Path(__file__).resolve().parents[2] / "packages/pvkit/src/models/irradiance/extra-radiation"


def ms(*args):
    return int(datetime(*args, tzinfo=timezone.utc).timestamp() * 1000)


def case(time_ms, method, solar_constant=1366.1, delta_t=67.0):
    t = pd.Timestamp(time_ms, unit="ms", tz="UTC")
    kw = dict(how="numpy", delta_t=delta_t) if method == "nrel" else {}
    v = pvlib.irradiance.get_extra_radiation(t, solar_constant=solar_constant, method=method, **kw)
    inp = dict(timeMs=time_ms, solarConstant=solar_constant, method=method)
    if method == "nrel":
        inp["deltaT"] = delta_t
    return {"input": inp, "expected": float(v)}


cases = []
fixed = [ms(2025, 1, 1, 0, 0, 0), ms(2025, 1, 3, 12, 0, 0), ms(2025, 7, 4, 23, 59, 59),
         ms(2024, 2, 29, 6, 0, 0), ms(2024, 12, 31, 23, 0, 0), ms(2023, 12, 31, 12, 0, 0),
         ms(1970, 1, 1, 0, 0, 0), ms(1900, 3, 1, 0, 0, 0), ms(2100, 6, 21, 0, 0, 0)]
for m in ("spencer", "asce", "nrel"):
    cases += [case(t, m) for t in fixed]
cases.append(case(ms(2025, 6, 1, 0, 0, 0), "spencer", 1361.0))
cases.append(case(ms(2025, 6, 1, 0, 0, 0), "nrel", 1367.0, 69.2))
rng = np.random.default_rng(20261005)
lo, hi = ms(1950, 1, 1, 0, 0, 0), ms(2080, 1, 1, 0, 0, 0)
for _ in range(40):
    t = int(rng.integers(lo, hi))
    cases += [case(t, m) for m in ("spencer", "asce")]
    cases.append(case(t, "nrel", 1366.1, float(rng.uniform(55, 75))))

meta = {"reference": f"pvlib.irradiance.get_extra_radiation(pd.Timestamp UTC) @ pvlib {pvlib.__version__}; "
        "method='nrel' passes how='numpy', delta_t"}
out = DIR / "extra-radiation-fixtures.json"
out.write_text(json.dumps({"meta": meta, "cases": cases}, indent=1) + "\n")
print(f"wrote {len(cases)} cases → {out}")


def fmt(x):
    return repr(float(x)).removesuffix(".0") if float(x).is_integer() else repr(float(x))


groups = ",\n".join(
    "  [\n" + "\n".join(f"    [{fmt(a)}, {fmt(b)}, {fmt(c)}]," for a, b, c in arr) + "\n  ]"
    for arr in (spa.R0, spa.R1, spa.R2, spa.R3, spa.R4)
)
(DIR / "earth-radius-terms.ts").write_text(f'''// biome-ignore-all lint/suspicious/noApproximativeNumericConstant: published coefficients (3.142 ≠ π), keep verbatim
/**
 * SPA Earth radius-vector periodic terms R0..R4 — Reda & Andreas (2008), NREL/TP-560-34302,
 * Table A4.2 (VSOP87 subset). Generated by scripts/fixtures/irradiance-extra-radiation.py from
 * pvlib {pvlib.__version__} `pvlib/spa.py`. Do not hand-edit.
 */

type Row3 = readonly [a: number, b: number, c: number];

/** Rows [A, B, C] → A·cos(B + C·JME); group i multiplies JME^i. */
export const R_TERMS: readonly (readonly Row3[])[] = [
{groups},
];
''')
